# Generated by Django 5.0.4 on 2024-04-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamsdatabase', '0002_alter_build_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admin',
        ),
    ]
